version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: rugby360_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: rugby360_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_config:/mosquitto/config

  node-red:
    image: nodered/node-red:latest
    container_name: rugby360_node-red
    ports:
      - "1880:1880"
    depends_on:
      - mosquitto

volumes:
  mongo_data:
  mosquitto_config:
